#!/bin/bash
set -x
BRIDGE=br0

NETMASK1=255.255.255.250
GATEWAY1=192.168.88.4

NETMASK2=255.255.255.0
GATEWAY2=10.172.10.3

function check_bridge() {
    if brctl show | grep "^${BRIDGE}" &> /dev/null; then
        return 1
    else
        return 0
    fi
}

function create_bridge() {
    brctl addbr ${BRIDGE}
    brctl stp ${BRIDGE} on
    ifconfig ${BRIDGE} ${GATEWAY1} netmask ${NETMASK1} up
    ifconfig ${BRIDGE}:1 ${GATEWAY2} netmask ${NETMASK2} up
}

function enable_ip_forward() {
    echo 1 > /proc/sys/net/ipv4/ip_forward
}

function setup_bridge() {
    check_bridge ${BRIDGE}
    if [ $? -eq 0 ]; then
        create_bridge
    fi
    enable_ip_forward
}
    
if [ -n $1 ]; then
    setup_bridge
    tunctl -u `whoami` -t $1
    ip link set $1 up
    sleep 0.5s
    brctl addif ${BRIDGE} $1
    exit 0
else
    echo "Error: no interface specified"
    exit 1
fi
